file:
    - 'tests/functional/api/users/index.js'
    - 'tests/functional/api/movies/index.js'
    - 'tests/functional/api/actors/index.js'
    - 'tests/functional/api/genres/index.js'

require: '@babel/register'
exit: true
timeout: 20000
